SprintRetrospective/Models/Project.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace SprintRetrospective.Models
{
    public class Project
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        public string Name { get; set; }

        [Required]
        public DateTime StartDate { get; set; }

        [Required]
        public int InitialVelocity { get; set; }

        [Required]
        public int HoursPerStoryPoint { get; set; }

        public int TeamId { get; set; }

        [ForeignKey("TeamId")]
        public Team Team { get; set; } // generates FK

        [Required]
        public string PivotalTrackerLink { get; set; }

        [Column(TypeName = "timestamp")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [MaxLength(8)]
        public byte[] Timer { get; set; }
    }
}

SprintRetrospective/Models/ProjectViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
namespace SprintRetrospective.Models
{
    public class ProjectViewModel
    {
        [Required(ErrorMessage = "Project name is required")]
        public string ProjectName { get; set; }
        [Required(ErrorMessage = "Link to Pivotal Tracker is required")]
        public string PivotalTrackerLink { get; set; }
        [Required(ErrorMessage = "Initial velocity is required")]
        public int InitialVelocity { get; set; }
        [Required(ErrorMessage = "Start Date is required")]
        public DateTime StartDate { get; set; }
        [Required(ErrorMessage = "Hours for each story point is required")]
        public int HoursPerStoryPoint { get; set; }
        public int Id { get; set; }
        public Project Project { get; set; }
        public List<Project> Projects { get; set; }
        public List<User> Users { get; set; }
        public int TeamId { get; set; }
        public Team Team { get; set; }
        public List<Team> Teams { get; set; }   // To be used to display all the teams so that when creating a project one can be chosen
        public IEnumerable<SelectListItem> GetProjects()
        {
            return Projects.Select(project => new SelectListItem { Text = project.Name, Value = project.Id.ToString() });
        }

        public IEnumerable<SelectListItem> GetTeams()
        {
            return Teams.Select(team => new SelectListItem { Text = team.Name, Value = team.Id.ToString() });
        }
    }
}

SprintRetrospective/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SprintRetrospective.Models;
using System.Collections.Generic;

namespace SprintRetrospective.Controllers
{
    public class ProjectController : Controller
    {
        AppDbContext _db;
        public ProjectController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            ProjectModel model = new ProjectModel(_db);
            ProjectViewModel viewModel = new ProjectViewModel();
            viewModel.Projects = model.GetAll();
            return View(viewModel);
        }

        public IActionResult Show(int id)
        {
            ProjectModel model = new ProjectModel(_db);
            ProjectViewModel viewModel = new ProjectViewModel();
            Project project = model.Get(id);
            viewModel.Id = project.Id;
            viewModel.ProjectName = project.Name;
            viewModel.StartDate = project.StartDate;
            viewModel.InitialVelocity = project.InitialVelocity;
            viewModel.PivotalTrackerLink = project.PivotalTrackerLink;
            viewModel.HoursPerStoryPoint = project.HoursPerStoryPoint;

            TeamModel tm = new TeamModel(_db);

            viewModel.Users = tm.GetUsers(project.TeamId);
            viewModel.Team = tm.Get(project.TeamId);
            return View(viewModel);
        }

        public IActionResult New()
        {
            ProjectModel model = new ProjectModel(_db);
            ProjectViewModel viewModel = new ProjectViewModel();

            TeamModel tm = new TeamModel(_db);
            viewModel.Teams = tm.GetAll();
            return View(viewModel);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> Create(ProjectViewModel projectVm)
        {
            TeamModel tm = new TeamModel(_db);
            if (ModelState.IsValid)
            {
                Project project = new Project();

                project.Name = projectVm.ProjectName;
                project.PivotalTrackerLink = projectVm.PivotalTrackerLink;
                project.InitialVelocity = projectVm.InitialVelocity;
                projectVm.Team = tm.Get(projectVm.TeamId);
                project.Team = projectVm.Team;
                project.InitialVelocity = projectVm.InitialVelocity;
                project.StartDate = projectVm.StartDate;
                project.HoursPerStoryPoint = projectVm.HoursPerStoryPoint;
                _db.Add(project);

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Show), new { id = project.Id });
            }
            else
            {
                projectVm.Teams = tm.GetAll();
                return View(nameof(New), projectVm);
            }
        }
    }
}

SprintRetrospective/Views/Project/Index.cshtml
@model ProjectViewModel
@{
    ViewData["Title"] = "Projects";
}

<h2>Projects</h2>
<form asp-controller="Project" asp-action="Show" method="get">
    <div class="col-sm-8 col-xs-12">
        <select asp-for="Id" asp-items="@Model.GetProjects()"
                class="form-group form-control" onchange="this.form.submit();">
            <option selected style="display:none;">Select Project</option>
        </select>
    </div>

    <p />
    <div class="col-sm-8 col-xs-12">
        <button type="submit" class="btn btn-primary" asp-controller="Project" asp-action="New" formmethod="get">
            Create New Project
        </button>
    </div>
</form>

SprintRetrospective/Views/Project/new.cshtml
@model ProjectViewModel
@{
    ViewData["Title"] = "Projects";
}

<h2 class="display-2">Create New Project</h2>
<form asp-controller="Project" asp-action="Create" method="post">
    <p/>
    <div class="form-group col-12">
        <label>Project Name:</label>
        <input type="text" asp-for="ProjectName" class="form-control">
        <span asp-validation-for="ProjectName" class="text-danger"></span>
    </div>
    <p />
    <div class="form-group col-12">
        <label>Team in Charge:</label>
        <select asp-for="TeamId" asp-items="@(new SelectList(Model.Teams,"Id","Name"))" class="form-control">
            <option selected style="display:none;">Select Team</option>
        </select>
    </div>
    <div class="form-group col-12">
        <label>Pivotal Tracker Link:</label>
        <input type="text" asp-for="PivotalTrackerLink" class="form-control">
        <span asp-validation-for="PivotalTrackerLink" class="text-danger"></span>
    </div>
    <div class="form-group col-12">
        <label>Initial Velocity:</label>
        <input type="text" asp-for="InitialVelocity" class="form-control" value="">
        <span asp-validation-for="InitialVelocity" class="text-danger"></span>
    </div>
    <p />
    <div class="form-group col-12">
        <label>Project Start Date:</label>
        <div class="input-group date datepicker" data-provide="datepicker">
            <input asp-for="StartDate" type="text" class="form-control" value="" readonly="readonly">
            <div class="input-group-addon glyphicon glyphicon-th"></div>
        </div>
    </div>
    <p />
    <div class="form-group col-12">
        <label>Hours Per Story Point:</label>
        <input type="text" asp-for="HoursPerStoryPoint" class="form-control" value="">
        <span asp-validation-for="HoursPerStoryPoint" class="text-danger"></span>
    </div>
    <p />
    <button type="submit" class="btn btn-primary">
        Create
    </button>
</form>

SprintRetrospective/Views/Project/show.cshtml
@model ProjectViewModel
@{
    ViewData["Title"] = @Model.ProjectName;
}

<div class="row">
    <div class="col-xs-4"><h1 style="margin-top: 6%;">@Model.ProjectName</h1></div>
    <div class="col-xs-4">
        <form asp-controller="Backlog" asp-action="Show" asp-route-id="@Model.Id" method="get">
            <button class="btn btn-primary backlog-btn" type="submit">
                View Backlog
            </button>
        </form>
    </div>
</div>
<h3 class="h3">Team: @Model.Team.Name</h3>
<h3 class="h3" style="margin-bottom: 50px;">Team Number: @Model.Team.Id</h3>
<p />
<div class="col-sm">
    @{
        if (Model.Users != null)
        {
            <h4 class="text-primary">Users assigned to the project:</h4>
            foreach (User user in Model.Users)
            {
                <div>@user.FirstName @user.LastName</div>
            }
        }
    }
</div>
<div class="col-sm" style="margin-top: 50px;">
    <p />
    <h4 class="text-primary">Project Information:</h4>
    <label>Start Date: @Model.StartDate.ToShortDateString()</label>
    <br />
    <label>Initial Velocity: @Model.InitialVelocity</label>
    <br />
    <label>Pivotal Tracker Link: <a href="@Model.PivotalTrackerLink">@Model.PivotalTrackerLink</a></label>
    <br />
    <label>Hours Per Story Point: @Model.HoursPerStoryPoint</label>
</div>