SprintRetrospective/Models/BacklogViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
namespace SprintRetrospective.Models
{
    public class BacklogViewModel
    {
        public BacklogViewModel() { }
        public Project Project { get; set; }
        public List<Story> Stories { get; set; }
        public List<UserStory> UserStories { get; set; }
        public List<Task> Tasks { get; set; }
        public Sprint CurrentSprint { get; set; }
        public List<Story> CurrentSprintStories { get; set; }
    }
}

SprintRetrospective/Controllers/BacklogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SprintRetrospective.Models;
using System.Collections.Generic;

namespace SprintRetrospective.Controllers
{
    public class BacklogController : Controller
    {
        AppDbContext _db;
        public BacklogController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Show(int id)
        {
            BacklogViewModel backlogViewModel = new BacklogViewModel();
            StoryModel storyModel = new StoryModel(_db);
            SprintModel sprintModel = new SprintModel(_db);
            ProjectModel projectModel = new ProjectModel(_db);

            backlogViewModel.Stories = storyModel.GetAllByProject(id);
            backlogViewModel.Project = projectModel.Get(id);
            backlogViewModel.CurrentSprint = sprintModel.Get(id);
            if (backlogViewModel.CurrentSprint != null)
            {
                backlogViewModel.CurrentSprintStories = storyModel.GetAllBySprint(backlogViewModel.CurrentSprint.Id);

                foreach (Story storyInSprint in backlogViewModel.CurrentSprintStories)
                    backlogViewModel.Stories.Remove(storyInSprint);
            }

            return View(backlogViewModel);
        }

        public IActionResult Details(int id)
        {
            StoryViewModel storyViewModel = new StoryViewModel();
            StoryModel storyModel = new StoryModel(_db);
            Story story = storyModel.Get(id);

            storyViewModel.Id = story.Id;
            storyViewModel.Name = story.Name;
            storyViewModel.Description = story.Description;
            storyViewModel.RelativeEstimate = story.RelativeEstimate;
            storyViewModel.HoursWorked = story.HoursWorked;
            storyViewModel.Tasks = storyModel.GetAllTasks(id);
            storyViewModel.ProjectId = story.ProjectId;
            storyViewModel.Status = story.Status;
            return View(storyViewModel);
        }

        public IActionResult New(int id)
        {
            StoryViewModel storyViewModel = new StoryViewModel();
            storyViewModel.ProjectId = id;

            return View(storyViewModel);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> Create(StoryViewModel storyVm)
        {
            if (ModelState.IsValid)
            {
                Story story = new Story();

                story.Name = storyVm.Name;
                story.Description = storyVm.Description;
                story.RelativeEstimate = storyVm.RelativeEstimate;
                story.ProjectId = storyVm.ProjectId;
                _db.Add(story);
                story.UserId = "";

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Show), new { id = story.ProjectId });
            }
            else
            {
                return View(nameof(New), storyVm);
            }
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> Update(StoryViewModel storyVm)
        {
            if (ModelState.IsValid)
            {
                Story story = new Story();

                story.Id = storyVm.Id;
                story.Name = storyVm.Name;
                story.Description = storyVm.Description;
                story.RelativeEstimate = storyVm.RelativeEstimate;
                story.ProjectId = storyVm.ProjectId;
                story.UserId = "";
                story.Status = storyVm.Status;
                _db.Update(story);

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Show), new { id = story.ProjectId });
            }
            else
            {
                return View(nameof(New), storyVm);
            }
        }
    }
}

SprintRetrospective/Views/Backlog/Details.cshtml
@model StoryViewModel
@{
    ViewData["Title"] = "Story Details";
}

<div class="container">
    <div class="row">
        <h2 class="h2">Story Details</h2>
    </div>
</div>
<form asp-controller="Backlog" asp-action="Update" method="post">
    <p />
    <div class="form-group col-12">
        <label>Story Name:</label>
        <input type="text" asp-for="Name" class="form-control" value="@Model.Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <p />
    <div class="form-group col-12">
        <label>Story Description:</label>
        <textarea type="text" asp-for="Description" class="form-control" rows="3">@Model.Description</textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group col-12">
        <label>Relative Estimate (in points):</label>
        <input type="text" asp-for="RelativeEstimate" class="form-control" value="@Model.RelativeEstimate">
        <span asp-validation-for="RelativeEstimate" class="text-danger"></span>
    </div>
    <div class="form-group col-12">
        <label>Status:</label>
        <select asp-for="Status" class="form-control">
            @{List<string> statuses = new List<string>() { "Planned", "Started", "Delivered" };}
            @foreach (string status in statuses)
            {
                if (status == Model.Status)
                {
                    <option selected="selected">@status</option>
                }
                else
                {
                    <option>@status</option>
                }
            }
        </select>
    </div>
    <p />
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="ProjectId" />
    <button type="submit" class="btn btn-primary">
        Update
    </button>
</form>

SprintRetrospective/Views/Backlog/New.cshtml
@model StoryViewModel
@{
    ViewData["Title"] = "Story";
}

<div class="container">
    <div class="row">
        <h2 class="h2">Create a New Story</h2>
    </div>
</div>
<form asp-controller="Backlog" asp-action="Create" method="post">
    <p />
    <div class="form-group col-12">
        <label>Story Name:</label>
        <input type="text" asp-for="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <p />
    <div class="form-group col-12">
        <label>Story Description:</label>
        <textarea type="text" asp-for="Description" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group col-12">
        <label>Relative Estimate (in points):</label>
        <input type="text" asp-for="RelativeEstimate" class="form-control" value="">
        <span asp-validation-for="RelativeEstimate" class="text-danger"></span>
    </div>
    <p />
    <input type="hidden" asp-for="ProjectId"/>
    <button type="submit" class="btn btn-primary">
        Create
    </button>
</form>

SprintRetrospective/Views/Backlog/Show.cshtml
@model BacklogViewModel
@{
    ViewData["Title"] = "Backlog";
}

<div class="container">
    <div class="row">
        <div class="col-xs-4"><h1 style="margin-top: 6%; font-weight: 300;">@Model.Project.Name Product Backlog</h1></div>
        <div class="col-xs-4">
            @using (Html.BeginForm("New", "Backlog", new { id = Model.Project.Id }))
            {
                <button type="submit" class="btn btn-primary backlog-btn">Add New Story</button>
            }
        </div>
    </div>
    <p />
    @if (@Model.CurrentSprint != null)
    {
        <h2 style="font-weight: 300;">Current Sprint (@Model.CurrentSprint.StartDate.ToShortDateString() - @Model.CurrentSprint.EndDate.ToShortDateString())</h2>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Story Name</th>
                    <th scope="col">Relative Estimate</th>
                    <th scope="col">Hours Worked</th>
                    <th scope="col">User Assigned</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Story story in Model.CurrentSprintStories)
                {
                    <tr>
                        <th scope="row">@story.Id</th>
                        <td>@Html.ActionLink(story.Name, "Details", new { id = story.Id })</td>
                        <td>@story.RelativeEstimate</td>
                        <td>@story.HoursWorked</td>
                        <td>@story.UserId</td>
                        <td>@story.Status</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    <h2 style="margin-top: 5%; font-weight: 300;">Backlog</h2>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Story Name</th>
                <th scope="col">Relative Estimate</th>
                <th scope="col">Hours Worked</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Story story in Model.Stories)
            {
                <tr>
                    <th scope="row">@story.Id</th>
                    <td>@Html.ActionLink(story.Name, "Details", new { id = story.Id })</td>
                    <td>@story.RelativeEstimate</td>
                    <td>@story.HoursWorked</td>
                </tr>
            }
        </tbody>
    </table>
</div>