SprintRetrospective/Models/Team.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SprintRetrospective.Models
{
    public class Team
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        public string Name { get; set; }
    }
}

SprintRetrospective/Models/TeamViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SprintRetrospective.Models
{
    public class TeamViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Team> Teams { get; set; }
        public List<User> Users { get; set; }
        public List<User> AllUsers { get; set; }
        public IEnumerable<SelectListItem> GetTeams()
        {
            return Teams.Select(team => new SelectListItem { Text = team.Name, Value = team.Id.ToString() });
        }

        public IEnumerable<SelectListItem> GetAllUsers()
        {
            return AllUsers.Select(user => new SelectListItem { Text = user.FirstName + " " + user.LastName, Value = user.Id.ToString() });
        }

        public IEnumerable<SelectListItem> GetTeamUsers()
        {
            return Users.Select(user => new SelectListItem { Text = user.FirstName + " " + user.LastName, Value = user.Id.ToString() });
        }
    }
}

SprintRetrospective/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SprintRetrospective.Models;

namespace SprintRetrospective.Controllers
{
    public class TeamController : Controller
    {
        AppDbContext _db;

        public TeamController(AppDbContext context)
        {
            _db = context;
        }

        public IActionResult Index()
        {
            UserModel userModel = new UserModel(_db);
            TeamViewModel viewModel = new TeamViewModel();
            viewModel.Teams = userModel.GetAllTeams();

            return View(viewModel);
        }

        public IActionResult Show(int id)
        {
            TeamModel model = new TeamModel(_db);
            TeamViewModel viewModel = new TeamViewModel();
            Team team = model.Get(id);
            viewModel.Id = team.Id;
            viewModel.Name = team.Name;
            viewModel.Users = model.GetUsers(team.Id);
            return View(viewModel);
        }

        public IActionResult New()
        {
            TeamModel model = new TeamModel(_db);
            TeamViewModel viewModel = new TeamViewModel();

            return View(viewModel);
        }

        public IActionResult Add(int id)
        {
            UserModel um = new UserModel(_db);
            TeamModel tm = new TeamModel(_db);
            TeamViewModel teamVm = new TeamViewModel();
            Team team = tm.Get(id);
            teamVm.Id = team.Id;
            teamVm.Name = team.Name;
            teamVm.Users = tm.GetUsers(id);

            teamVm.AllUsers = um.GetAll();

            foreach(var u in teamVm.Users)
            {
                teamVm.AllUsers.Remove(u);
            }

            return View(teamVm);
        }

        public IActionResult Remove(int id)
        {
            UserModel um = new UserModel(_db);
            TeamModel tm = new TeamModel(_db);
            TeamViewModel teamVm = new TeamViewModel();
            Team team = tm.Get(id);
            teamVm.Id = team.Id;
            teamVm.Name = team.Name;
            teamVm.Users = tm.GetUsers(id);

            return View(teamVm);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> AddMember(string id)
        {
            TeamModel tm = new TeamModel(_db);
            int teamId = Int32.Parse(HttpContext.Request.Query["teamid"]);
            Team team = tm.Get(teamId);

            // Get information for current team;
            TeamViewModel teamVm = new TeamViewModel();
            teamVm.Id = team.Id;
            teamVm.Name = team.Name;
            UserModel um = new UserModel(_db);
            User newUser = um.Get(id);

            UserTeam newUserTeam = new UserTeam { Team = team, User = newUser };
            _db.Add(newUserTeam);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Show), teamVm);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> RemoveMember(string id)
        {
            TeamModel tm = new TeamModel(_db);
            int teamId = Int32.Parse(HttpContext.Request.Query["teamid"]);
            Team team = tm.Get(teamId);

            // Get information for current team;
            TeamViewModel teamVm = new TeamViewModel();
            teamVm.Id = team.Id;
            teamVm.Name = team.Name;
            UserModel um = new UserModel(_db);
            User removeUser = um.Get(id);

            UserTeam newUserTeam = tm.GetUserTeam(team, removeUser, id);
            _db.Remove(newUserTeam);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Show), teamVm);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> Create(TeamViewModel teamVm)
        {
            TeamModel tm = new TeamModel(_db);
            if (ModelState.IsValid)
            {
                Team team = new Team();

                team.Name = teamVm.Name;
                _db.Add(team);

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Show), new { id = team.Id });
            }
            else
            {
                teamVm.Teams = tm.GetAll();
                return View(nameof(New), teamVm);
            }
        }
    }
}

SprintRetrospective/Views/Team/Add.cshtml
@model TeamViewModel
@{
    ViewData["Title"] = "Add Team Member";
}

<div class="container">
    <div class="row">
        <h2>Team: @Model.Name</h2>
    </div>
    <div class="row">
        <form asp-controller="Team">
            <select asp-for="Id" asp-items="@Model.GetAllUsers()" class="form-group form-control">
                <option selected style="display:none;"></option>
            </select>
            <button type="submit" class="btn btn-primary"
                    asp-controller="Team" asp-action="Addmember" formmethod="post" asp-route-teamid="@Model.Id">
                Add Team Member
            </button>
            <button onclick="history.go(-1)" type="button" class="btn btn-danger">Back</button>
        </form>
    </div>
</div>

SprintRetrospective/Views/Team/Index.cshtml
@model TeamViewModel
@{
    ViewData["Title"] = "Teams";
}

<div class="container">
    <div class="row">
        <h2>Teams</h2>
    </div>
    <div class="row">
        <form asp-controller="Team" asp-action="Show" method="get">
                <select asp-for="Id" asp-items="@Model.GetTeams()"
                        class="form-group form-control" onchange="this.form.submit();">
                    <option selected style="display:none;">Select Team</option>
                </select>

            <p />
                <button type="submit" class="btn btn-primary" asp-controller="Team" asp-action="New" formmethod="get">
                    Create New Team
                </button>
        </form>
    </div>
</div>

SprintRetrospective/Views/Team/New.cshtml
@model TeamViewModel
@{
    ViewData["Title"] = "Create New Team";
}
<h2 class="h3">Create New Project</h2>
<form asp-controller="Team" asp-action="Create" method="post">
    <p />
    <div class="form-group">
        <label>Team Name:</label>
        <input type="text" asp-for="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">
        Create Team
    </button>
</form>

SprintRetrospective/Views/Team/Remove.cshtml
@model TeamViewModel
@{
    ViewData["Title"] = "Remove Team Member";
}

<div class="container">
    <div class="row">
        <h2>Team: @Model.Name</h2>
    </div>
    <div class="row">
        <form asp-controller="Team">
            <select asp-for="Id" asp-items="@Model.GetTeamUsers()" class="form-group form-control">
                <option selected style="display:none;"></option>
            </select>
            <button type="submit" class="btn btn-primary"
                    asp-controller="Team" asp-action="RemoveMember" formmethod="post" asp-route-teamid="@Model.Id">
                Remove Team Member
            </button>
            <button onclick="history.go(-1)" type="button" class="btn btn-warning">Back</button>
        </form>
    </div>
</div>

SprintRetrospective/Views/Team/Show.cshtml
@model TeamViewModel
@{
    ViewData["Title"] = @Model.Name;
}

<div class="container">
    <div class="row">
        <h1 class="h1">@Model.Name</h1>
    </div>
    <div class="row">
        <h3 class="h3" style="margin-bottom: 25px;">Team Number: @Model.Id.ToString()</h3>
    </div>


    @{
        if (Model.Users != null && Model.Users.Count != 0)
        {
            <div class="row">
                <h4 class="text-primary">Members assigned to the team:</h4>
            </div>
            <div class="row">
                <div class="col-sm">
                    @foreach (User user in Model.Users)
                    {
                        <div>@user.FirstName @user.LastName</div>
                    }
                </div>
                .
            </div>
        }
        else
        {
            <div class="row">
                <h4 class="text-primary">Team has 0 members</h4>
            </div>
        }
    }

    <div class="row">
            @{
                <a asp-area="" class="btn btn-primary m-1" asp-controller="Team" asp-action="Add" asp-route-id="@Model.Id">
                    Add Member
                </a>
                <a asp-area="" class="btn btn-danger m-1" asp-controller="Team" asp-action="Remove" asp-route-id="@Model.Id">
                    Remove Member
                </a>
            }
    </div>
</div>